### ISSUE TITLE
callback function parameters are displaced.

### ISSUE THREAD

**Issue by ahgilak** [asos-craigmorten/superoak#10]
# Issue

Setup:

- Deno Version: 1.5.3
- v8 Version: 8.7.220.3
- Typescript Version: 4.0.5
- SuperOak Version: 2.3.1

Callback function parameters are displaced.

## Details

I want to use callback function like below but the test fails because res is undefined.
```typescript
Deno.test("test", async () => {
  const req = await superoak(app);
  await req.post("/").expect((err, res) => {
    expect(res.body.message).toEqual("Hello Deno!");
  });
});
```
Callback described as  `CallbackHandler(err: any, res: IResponse): void` in typescript autocomplete, but actually the first argument contains response value so it should be `CallbackHandler(res: IResponse, err: any): void`.

**Comment by asos-craigmorten** [comment]
@ahgilak thanks for flagging this!

Would this be something that you would be willing to be a put in a pull request to fix? No worries if not! I will endeavour to find some time to take a look 😄

**Comment by cmorten** [comment]
The issue lies upstream with https://github.com/asos-craigmorten/superdeno which has 🤞 just been fixed, should drop in my PR with an update to dependency versions!
