### ISSUE TITLE
Does not send correctly an application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by DanielRamosAcosta** [asos-craigmorten/superoak#27]
# Issue

Setup:

- Deno Version: 1.17.0 (release, aarch64-apple-darwin)
- v8 Version: 9.7.106.15
- Typescript Version: 4.5.2
- SuperOak Version: 4.5.0

## Details

When sending a form like:

```ts
superoak(app)
  .post("/")
  .type("form")
  .field("hello", "world")
  .field("foo", "bar")
```

Instead of receiving `{hello: "world", foo: "bar"}` I'm receiving the following:

```
{
  "------9219543305020510994576475827\r\nContent-Disposition: form-data; name": '"hello"\r\n\r\nworld\r\n------9219543305020510994576475827\r\nContent-Disposition: form-data; name="foo"\r\n\r\n...'
}
```

I'm going to open a PR with a failing test to validate this

**Comment by cmorten** [comment]
Afaik there may have been some confusion here…

- for `x-www-form-urlencoded requests` you can just use the `.send()` API. Ref: https://visionmedia.github.io/superagent/#post--put-requests
- the `.field()` you have used here is for `multipart/form-data` requests. Ref: https://visionmedia.github.io/superagent/#multipart-requests

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST#example for some examples highlighting the request differences.

Instead try…

```ts
const request = await superoak(app);

await request.post("/")
  .send("hello=world&foo=bar");
```

or similar variations 😄

**Comment by DanielRamosAcosta** [comment]
That's right!

I ended doing:

```ts
await request.post("/")
  .type("form")
  .send({ hello: "world", foo: "bar" })
```
